### PR TITLE
CSS styling

### PR DESCRIPTION
**Pull request by sherrynance**
Update image links for all pages.

### CODE REVIEW

**Comment by amymcgowan** [comment]
Hey @sherrynance.  It looks like there are conflicts here.  

Are you able to see what it should be by clicking the Resolve conflicts button up there ^^ and fixing it?  If not, might need to go into the branch on your computer and do a 

git pull ... from the master branch
git merge master .... from the css-styling branch

Resolve any conflicts and then push the branch again ... does that make sense?

**Comment by sherrynance** [comment]
This one should have been deleted.  I thought I did that. I was going to do an image folder but we decided to keep imgur.

**Comment by sherrynance** [comment]
This one should have been deleted.  I thought I did that. I was going to do an image folder but we decided to keep imgur.

**Comment by amymcgowan** [comment]
gotcha 👍

**Pull request closed without merging**
