### PR TITLE
make headlines bold for help-others and find-help pages

### PR DESCRIPTION
**Pull request by aikot1125**
- make headlines of each green box bold for help-others and find-help pages so that they are consistent with the food-tips page

### CODE REVIEW

**Comment by andreamartz** [comment]
@aikot1125 @amymcgowan 
Because this PR came after the one that I closed, I am going to ask you to resubmit it, Aiko.  Please pull down the repo, make sure there are no merge conflicts, and re-push.  Thanks!

**Comment by amymcgowan** [comment]
@andreamartz , The PR would say if there are now new merge conflicts due to previous changes.  I believe the "This branch has no conflicts with the base branch" is dynamic and is always checking even after the initial PR is made, so this should be fine

**Comment by amymcgowan** [comment]
@andreamartz I think this is fine to merge.  What do you think?

**Comment by andreamartz** [comment]
@amymcgowan @aikot1125 
It is fine to merge only if we want to re-introduce the code from PR #51 which is still in there.  If I understood correctly from Slack, we don't want to do that.  That is, we want to leave "Share this site..." in the green box.  PR #51 was proposing to take it out of the green box.

Let me put it another way: PR #51 was Aiko's.  She rightly kept her code from PR #51 in there when she created PR #52 (i.e., this PR).  The problem is that PR #51 was closed without being merged into master.  Therefore, even though PR #52 doesn't have conflicts with master, it contains code that we decided (I think) shouldn't be there.

**Comment by andreamartz** [comment]
@aikot1125 @amymcgowan 
Is there something I'm missing in my logic?  I know there are no merge conflicts, but I still see the PR #51 code in there.

**Comment by aikot1125** [comment]
not sure why "fix 'share this site' section on help others page" commit remained on this PR.. 
I can resubmit, but in that case do I need to edit the code again? Just wondering if there is a way to keep part of these commits when I resubmit.

**Comment by andreamartz** [comment]
If I'm understanding your question correctly, it remained there because you rightly assumed that your PR #51 would be accepted, so you left that code in your file when you pushed PR #52.

I think all you need to do is:

1. Do a ```git pull``` from your master to bring the current repo state into your local.
2. Go to your ```at-create-headline``` branch and do ```git merge master```. 
3. Redo your changes from PR #52 (this PR).
4. Add, commit, and push.

**Comment by amymcgowan** [comment]
@aikot1125 @andreamartz I'm pretty sure there is a way to remove a commit from a PR.  I can't look into it right now, but can a little later

**Comment by andreamartz** [comment]
@aikot1125 @amymcgowan 
*Quick version:* I don't think that removing the commit will help.  But if we want to take a short cut, Aiko could just add another commit to this PR that just manually undoes what she did in PR #51.  PR #51 was very, very small.  This is probably not a best practice, but that's just a guess.

*Longer version:*
So, this is what I believe may have happened based on what I am seeing.  I'm explaining this so that you can review my logic for why I think that removing the commit will not help.
1. Aiko pushed branch ```at-fix-share-button``` with a single commit which became PR #51.
2. She then did a ```git merge at-fix-share-button``` while on master to bring those PR #51 changes into her local master branch.
3. She then created another branch from master called ```at-create-headline``` (which contained the changes made in PR #51).
4. She made the changes and commits for this PR (#52) on the ```at-create-headline``` branch.  Then, she pushed to the repo and created this PR.

Aiko, if you've made it this far, please let me know if that is all accurate.

Assuming it is accurate, I've not run into this issue before, but it seems to me that just removing that one commit from the other branch wouldn't solve the problem, because it was merged into her local master.

I'm happy to get on a call today to get this worked out.  I have just a few errands to run, so knowing in advance when the call would be will help me.

**Comment by amymcgowan** [comment]
@aikot1125 , I think @andreamartz's suggestion 3 comments before this one where she says "I think all you need to do is:..." are the best way forward.

**Comment by aikot1125** [comment]
Thanks for the advice @andreamartz  and @amymcgowan ! I re-submitted the PR.

**Comment by amymcgowan** [comment]
I am closing this PR for the time being.  We can reopen it down the road if need be.  Thanks for all your hard work!

**Pull request closed without merging**
