### PR TITLE
Organize HTML & CSS into folders

### PR DESCRIPTION
**Pull request by andreamartz**
Create folders for HTML and CSS files.
Begin index.html

### CODE REVIEW

**Comment by amymcgowan** [comment]
There's an about.css file in the html directory.  Is that supposed to be about.html?

**Comment by amymcgowan** [comment]
I like index.html back in the root. 👍 nice.

**Comment by andreamartz** [comment]
1. Thanks for finding the typo (about.css)
2. Yes, I was thinking about it, and I think I remember that index.html has to stay in the root.

**Comment by amymcgowan** [comment]
Perfect!  
And, yes, I think you're right about the index file.  Something about the browser knowing to find it in the root or such.  :)

**Pull request merged**
