### PR TITLE
Icon accessibility

### PR DESCRIPTION
**Pull request by sherrynance**
added aria-hidden="true" to all of the font awesome icons

### CODE REVIEW

**Comment by andreamartz** [comment]
@sherrynance @amymcgowan 
This looks great in so many ways, and I so appreciate your help!  I did notice, though, that you added aria-hidden="true" to the hamburger menu on all pages.  I think we need to take that off so that the mobile menu will be accessible to screen readers. So sorry that I didn't think to mention this before you did your work.

I think you can just undo that for each file and do new commits.  We'll wait to merge to master until you say you're ready.  Thanks Sherry!

**Comment by andreamartz** [comment]
@sherrynance @amymcgowan 
I also just noticed that you put aria-hidden="true" on the copyright icon.  Since that one was semantic, not decorative, how did Font Awesome recommend handling it?

**Comment by sherrynance** [comment]
Font awesome has it as "<i class="fa fa-copyright" aria-hidden="true"></i> and now that I have thought about it shouldn't we have the word copyright in written in the footer?  Maybe that is why don't awesome says it's a decorative icon?

**Comment by andreamartz** [comment]
@sherrynance @amymcgowan 
Figma shows only the copyright symbol, not the word.
  
I'm not sure I completely understood your response.  Did Font Awesome explain how to handle semantic icons?

**Comment by andreamartz** [comment]
@sherrynance @amymcgowan 
How can I help?  I so appreciate everyone's help with the accessibility work, and I don't want to make anyone regret helping.  : )   

Should we just merge this PR and then I'll make the changes?  It's not the best way to do things, but time is of the essence.

**Re: hamburger menu accessibility**
Also, I just found this resource which discusses how to make hamburger menus accessible: [Accessibility for Hamburger Menu](https://medium.com/@linlinghao/accessibility-for-hamburger-menu-a37fa9617a89)  

This article indicates that we would actually keep the aria-hidden attribute but also add some other code.

**Comment by sherrynance** [comment]
Sorry I was in a low cell zone  and hit send before I needed too. I asked @amymcgowan about the copyright symbol. I think it would be just as easy to just include the word copyright with the symbol in the footer. It's done that way on many websites. 

As for the hamburger menu I only put in what font awesome suggested after saying that I looked up all the icons and that is what font awesome suggested to do. I'm happy to change it and put in whatever is necessary. But from our earlier conversation on Slack I thought I was doing what I was supposed to.

**Comment by andreamartz** [comment]
Response coming... I'm on the phone...

**Comment by sherrynance** [comment]
I agree that the hamburger menu probably does need different code.  Our code currently says "toggle navigation"

Screenshot (99)

The website above says "open the menu"

Screenshot (100)

I am asking if we want to change it to this?  As far as I can see this is the only difference.  Because this is a bootstrap navigation menu I'm not sure which pieces of the code we have are bootstrap.  I'm not sure if this makes sense.  I'm just relaying what I am seeing in our code versus the website you linked above.

**Comment by andreamartz** [comment]
I'm not sure.  I definitely don't want to put the wrong code in or not enough of the right code and end up making things worse.  We need to really understand any code we put in, what it does, what it doesn't do, and why we're using it. 

The code in the gray box doesn't tell the whole story of how our code needs to change.  There, they show the <i> tag inside of the <a> tag.  That's not how our code is written.  Our <i> tag is inside of (a <span> that's inside of) a <button>.

I don't feel like I know yet exactly how the code needs to change, but I can look into it. Ideally, I'd be able to find a resource that tells us how to make a Bootstrap 4 navbar hamburger icon mobile accessible.  That's what I'll look for now unless you've already researched this and have a good idea of what we need to do.

**Comment by sherrynance** [comment]
Amy ok'd the addition of Copyright to the footer to make the icon decorative. 

I have been looking for information about bootstrap and accessibility for the toggle menu but I can't find it. Their information says that their framework is built to be as accessible as possible. Not sure what that means?  But I am searching. I will change the footer and push.  

Do you want me to remove the aria-hidden tag from the icon on the hamburger menu while I am there and hopefully we can figure that part out next?

**Comment by andreamartz** [comment]
I think that sounds great!  This is what I understand you to be saying:
1. You'll add "Copyright" to the footer on all six pages, right? I think that makes the icon redundant, but let's just get it done.
2. And you'll remove the aria-hidden attribute from all hamburger menu icons.
If I've got that right, go for it!

**Comment by amymcgowan** [comment]
I'm busy doing something else right now and had to skim the last part.  I can revist in an hour or so if this is still open.  Just wanted to comment that, yes, the copyright part should have both the word and the symbol.  That's the best way to do it from my research and the way it was originally written on the Trello card.

**Pull request closed without merging**
